---
- name: Download latest Upgrade Go script
  get_url:
    url: "https://git.io/upgradego"
    dest: /usr/local/bin/upgrade_go.sh
    owner: "{{ userid.stdout }}"
    mode: 0755

# archive name: {{ go_version}}.{{ os_name }}-{{ arch }}.tar.gz
- name: Get and unarchive latest go archive
  unarchive:
    src: https://dl.google.com/go/{{ lookup('url', 'https://golang.org/VERSION?m=text', split_lines=False) }}.linux-amd64.tar.gz
    dest: /usr/local
    remote_src: yes

- name: Set GOPATH in users .bashrc 
  lineinfile:
    path: "/home/{{ userid.stdout }}/.bashrc"
    line: export GOPATH="/data/code/go"
    insertafter: SYSTEMD_PAGER=

- name: Update $PATH with $GOROOT/bin
  lineinfile:
    path: "/home/{{ userid.stdout }}/.bashrc"
    line: export PATH="$PATH:/usr/local/go/bin"
    insertafter: SYSTEMD_PAGER=
