---
- name: Remove docker if already installed
  yum:
    name: "{{ item }}"
    state: absent
  with_items:
  - docker
  - docker-client
  - docker-client-latest
  - docker-common
  - docker-latest
  - docker-latest-logrotate
  - docker-logrotate
  - docker-engine

- name: Import official docker-ce yum repository gpg key
  rpm_key:
    key: https://download.docker.com/linux/centos/gpg
    state: present

- name: Add official docker-ce yum repository
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    force: yes
    owner: root
    group: root
    mode: 0644

- name: Install docker-ce
  yum:
    name: docker-ce
    state: present
    update_cache: yes

- name: Start docker.service
  service:
    name: docker
    state: started
    enabled: yes

- name: "Add user {{ userid.stdout }} to docker group"
  user:
    name: "{{ userid.stdout }}"
    groups: docker
    append: yes

#- name: Install docker python module
#  pip:
#    name: docker
#    executable: pip
#    state: latest

#- name: Upgrade docker-py python module
#  pip:
#    name: docker-py
#    executable: pip
#    state: latest

#- name: Test pull an image
#  docker_image:
#    name: hello-world
#    source: pull
