---
- hosts: all
  sudo: yes
  #gather_facts: no
  vars_files:
    - group_vars/main.yaml
  vars:
    whoami: "{{ lookup('env','USER') }}"
  tasks:
    - name: Print some info
      debug: 
        msg: "User: '{{ whoami }}' System: '{{ ansible_distribution }}' UUID: '{{ ansible_product_uuid }}'"

    # ansible distros: https://git.io/Jeqae (in ansible/lib/ansible/module_utils/facts/system/distribution.py#L467)
    # https://docs.ansible.com/ansible/latest/user_guide/playbooks_conditionals.html#ansible-distribution

    - name: "Run OS specific tasks [CentOS]"
      include_tasks: tasks/centos.yaml
      when: ansible_distribution == "CentOS" or ansible_distribution == "Fedora"

    - name: "Run OS specific tasks [Debian]"
      include_tasks: tasks/debian.yaml
      when: ansible_os_family == "Debian" or ansible_distribution == "Ubuntu"

    - name: "Run OS specific tasks [CoreOS]"
      include_tasks: tasks/coreos.yaml
      when: ansible_os_family == 'CoreOS'

#    # Keep these here since this playbook will be used elsewhere
#    - name: "Run OS specific tasks [RedHat]"
#      include_tasks: tasks/redhat.yaml
#      when:
#        - ansible_os_family == "RedHat"
#        - ansible_distribution != "CentOS"
#
#    - name: "Run OS specific tasks [Darwin]"
#      include_tasks: tasks/darwin.yaml
#      when: ansible_os_family == 'Darwin'
#
#    - name: "Run OS specific tasks [FreeBSD]"
#      include_tasks: tasks/freebsd.yaml
#      when: ansible_distribution == 'FreeBSD'
#
#    - name: "Run OS specific tasks [Solaris]"
#      include_tasks: tasks/solaris.yaml
#      when: ansible_distribution == 'Solaris'
#
#    - name: "Run OS specific tasks [AIX]"
#      include_tasks: tasks/aix.yaml
#      when: ansible_distribution == 'AIX'
#
#    - name: "Run OS specific tasks [HP-UX]"
#      include_tasks: tasks/hpux.yaml
#      when: ansible_distribution == 'HP-UX'

    - name: Run tasks to install new do-agent
      include_tasks: tasks/do-agent.yaml

    - name: Run tasks to create required directories
      include_tasks: tasks/mkdir.yaml

    - name: Run tasks to download sysinfo.sh script
      include_tasks: tasks/sysinfo.yaml

    - name: Run tasks to install latest version of Go
      include_tasks: tasks/go.yaml

    - name: Run tasks to clone git repos
      include_tasks: tasks/git-clone.yaml

#EOF
