---
- hosts: all
  sudo: yes
  #gather_facts: no
  vars:
    whoami: "{{ lookup('env','USER') }}"
  tasks:

#### DEBUGGING START
    - name: Print some info
      debug: 
        msg: "User: '{{ whoami }}' System: '{{ ansible_distribution }}' UUID: '{{ ansible_product_uuid }}'"

    - name: Verify ansible version
      command: ansible --version
      register: ansver

    - name: Print ansible version
      debug:
        msg: "ansible version: {{ ansver.stdout }}"

    - name: Display all variables/facts known for a host
      debug:
        var: hostvars[inventory_hostname]
        verbosity: 4
#### DEBUGGING END

    # https://docs.ansible.com/ansible/latest/modules/yum_module.html
    - name: Update Red Hat based systems
      yum: >
        update_cache=yes
        name=*
        state=latest
        update_cache=yes
      when: >
        ansible_distribution == 'CentOS'
        or
        ansible_distribution == 'RedHat'

    # https://docs.ansible.com/ansible/latest/modules/apt_module.html
    - name: Update Debian based systems
      apt: >
        update_cache=yes
        cache_valid_time=1200
        upgrade=dist
      when: >
        ansible_distribution == 'Debian'
        or
        ansible_distribution == 'Ubuntu'

    - name: Remove the old do-agent package
      yum:
        name: do-agent
        state: absent
      when: >
        ansible_distribution == 'CentOS'
        or
        ansible_distribution == 'RedHat'

    - name: Remove the old do-agent package
      apt:
        name: do-agent
        state: absent
      when: >
        ansible_distribution == 'Debian'
        or
        ansible_distribution == 'Ubuntu'

    - name: Install packages via yum
      yum:
        name: "{{ packages }}"
      vars:
        packages:
        - vim
        - tar
        - gzip
        - curl
        - wget
        - gcc
        - gcc-c++
        - kernel-devel
        - yum-utils
        - make
        - perl
      when: >
        ansible_distribution == 'CentOS'
        or
        ansible_distribution == 'RedHat'

    - name: Install packages via apt
      apt:
        name: "{{ packages }}"
      vars:
        packages:
        - vim
        - tar
        - gzip
        - curl
        - wget
        - build-essential
        - linux-headers-generic
        - manpages-dev
        - perl
        - software-properties-common
        - python3-pip
        - python3-venv
        - libssl-dev
        - libffi-dev
        - python-dev
      when: >
        ansible_distribution == 'Debian'
        or
        ansible_distribution == 'Ubuntu'

    - name: Remove deps no longer required
      apt:
        autoremove: yes
      when: >
        ansible_distribution == 'Debian'
        or
        ansible_distribution == 'Ubuntu'

    - name: Download new do-agent install script
      get_url:
        url: https://repos.insights.digitalocean.com/install.sh
        dest: /tmp/do-agent-install.sh
        mode: '0770'

    - name: Install new do-agent
      command: bash /tmp/do-agent-install.sh

    - name: Get username for first UID
      shell: "awk -v val=1001 -F: '$3==val{print $1}' /etc/passwd"
      register: userid

    - name: Download latest Upgrade Go script
      get_url:
        url: "https://git.io/upgradego"
        dest: /usr/local/bin/upgrade_go.sh
        owner: "{{ userid.stdout }}"
        mode: 0755

    - name: Download latest sysinfo.sh script
      get_url:
        url: "https://git.io/sysinfo.sh"
        dest: /usr/local/bin/sysinfo.sh
        owner: "{{ userid.stdout }}"
        mode: 0755

    - name: Create code/build directories
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ userid.stdout }}"
        group: "{{ userid.stdout }}"
        mode: 0700
        #mode: "u=rwx,g=rw,o=rw"
      with_items:
        - /data
        - /data/code
        - /data/build

    - name: Create link to code in $HOME
      file:
        src: /data/code
        dest: "/home/{{ userid.stdout }}/code"
        owner: "{{ userid.stdout }}"
        group: "{{ userid.stdout }}"
        state: link


# TODO:
# install latest go
# set go paths
# install X???
# install IDE
# import ssh keys???
# clone repos
# curl -o tempfile.tmp -sfL ${GITHUB_URL}/download/${VERSION}/archivename${SUFFIX}
